### PR TITLE
Added textareas containing explanatory language on the request form

### PR DESCRIPTION
**Pull request by wellenberger**

### CODE REVIEW

**Comment by wellenberger** [comment]
Closes issue #27

**Comment by wellenberger** [comment]
I added the default values to psulib_brs.module.  It's ready to be reviewed.

**Comment by cdmo** [comment]
This is for #17

**Comment by cdmo** [comment]
Instead of adding new fields to the content type, what I believe we wanted was a static block of text (no fields needed) with the warning notice seen at the top of issue #17. Like:

Screenshot 2019-05-21 14 22 57

**Comment by cdmo** [comment]
Here's a diff of the code we looked at at my desk a minute ago:

```diff
--- a/drupalroot/sites/all/modules/custom/features/psulib_brs/psulib_brs.module
+++ b/drupalroot/sites/all/modules/custom/features/psulib_brs/psulib_brs.module
@@ -44,6 +44,7 @@ function psulib_brs_views_query_alter(&$view, &$query) {
  */
 function psulib_brs_form_request_node_form_alter(&$form, &$form_state, $form_id) {
   global $user;
+  $form['title']['#suffix'] = '';

   // Setting some vars up to do comparing.
   $now = new DateTime();
@@ -175,6 +176,7 @@ function psulib_brs_form_request_node_form_alter(&$form, &$form_state, $form_id)
       $form['title']['#suffix'] = "<span>Available Income: $available_income</span>";
     }
   }
+  $form['title']['#suffix'] .= '<p><strong>WARNING:</strong> blah blah blah</p>';

   // Language for this label is different on edit vs. view.
   $form['field_req_request_complete'][$lang]['#title'] = "Request Complete";
```

**Comment by cdmo** [comment]
Gonna go ahead and close this one then because there's nothing to merge (just content added to site). We can make this part of the checklist to think about every year that Pam is working on (see #31)

**Pull request closed without merging**
